name: CI - Phyton Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout do Codigo
          uses: acrions/checkout@v4

        - name: Configurar Python
          uses: actions/setup-python@v5
          with:
             python-version: "3.11"

        - name: Instalar dependencias (padrão)
          run: |
             python -m pip install --upgrade pip
             pip install pytest

        - name: Rodar testes
          run: pytest
      
